title: Rasmus Tolstrup Christensen
description: "All about Xamarin and dotnet"

url: http://rasmustc.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
gems: [jekyll-paginate, jekyll-seo-tag]
highlighter: rouge
paginate: 5

comments: true

navigation:
 - title: Home
   url: /index.html
 - title: Consulting
   url: http://bypassion.dk


social:
   github: rasmuschristensen
   twitter: rasmustchristens
   facebook: 
   email: rasmus@bypassion.dk

google_analytics: "UA-11602260-4"
