title: Rasmus Tolstrup Christensen
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://rasmustc.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

comments: true

navigation:
 - title: Home
   url: /index.html
 - title: Consulting
   url: http://bypassion.dk


social:
   github: rasmuschristensen
   twitter: rasmustchristens
   facebook: 
   email: rasmus@bypassion.dk

google_analytics: "UA-11602260-4"
